----------------
--ROLES
----------------

CREATE ROLE DEVELOPER;
CREATE ROLE TESTER;
CREATE ROLE ANALYST;

----------------
-- DEVELOPER
----------------


GRANT CONNECT, CREATE SESSION TO DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.CASE_DETAILS to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.CASE_RESOLUTION to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.CUSTOMER to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.CUSTOMER_ADDRESS to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.CUSTOMER_FEEDBACK to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.DEPARTMENT to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.DEPARTMENT to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.EMPLOYEE to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.EMPLOYEE_ADDRESS to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.EMPLOYEE_WORK to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.GEO_DETAILS to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.IMEI_INFO to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.PARTS to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.PAYMENT to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.PRODUCT to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.SUBSCRIPTION to DEVELOPER;
GRANT INSERT, UPDATE, DELETE, SELECT ON SHRIYA_PROJECT.SUBSCRIPTION_RENEWAL to DEVELOPER;


GRANT ALL ON SHRIYA_PROJECT.P_CASE_DETAILS TO DEVELOPER;
GRANT ALL ON SHRIYA_PROJECT.PCKG_CUSTOMER TO DEVELOPER;
GRANT ALL ON SHRIYA_PROJECT.PCKG_UTILS TO DEVELOPER;
GRANT ALL ON SHRIYA_PROJECT.PCKG_PAYMENT TO DEVELOPER;
GRANT ALL ON SHRIYA_PROJECT.PCKG_CASE_RESOLUTION TO DEVELOPER;
GRANT ALL ON SHRIYA_PROJECT.PCKG_EMPLOYEE_WORK TO DEVELOPER;
GRANT ALL ON SHRIYA_PROJECT.PCKG_UTILS TO DEVELOPER;


-------------
--TESTER
-------------

GRANT CONNECT, CREATE SESSION TO TESTER;
GRANT SELECT, INSERT ON SHRIYA_PROJECT.CASE_DETAILS to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.CASE_RESOLUTION to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.CUSTOMER to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.CUSTOMER_ADDRESS to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.CUSTOMER_FEEDBACK to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.DEPARTMENT to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.EMPLOYEE to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.EMPLOYEE_ADDRESS to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.EMPLOYEE_WORK to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.GEO_DETAILS to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.IMEI_INFO to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.PARTS to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.PAYMENT to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.PRODUCT to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.SUBSCRIPTION to TESTER;
GRANT INSERT, SELECT ON SHRIYA_PROJECT.SUBSCRIPTION_RENEWAL to TESTER;


GRANT EXECUTE ON SHRIYA_PROJECT.P_CASE_DETAILS TO TESTER;
GRANT EXECUTE ON SHRIYA_PROJECT.PCKG_CUSTOMER TO TESTER;
GRANT EXECUTE ON SHRIYA_PROJECT.PCKG_UTILS TO TESTER;
GRANT EXECUTE ON SHRIYA_PROJECT.PCKG_PAYMENT TO TESTER;
GRANT EXECUTE ON SHRIYA_PROJECT.PCKG_CASE_RESOLUTION TO TESTER;
GRANT EXECUTE ON SHRIYA_PROJECT.PCKG_EMPLOYEE_WORK TO TESTER;

GRANT ALL ON RECIEPT_VW TO TESTER;
GRANT ALL ON V_CASE_DETAILS TO TESTER;
GRANT ALL ON V_CUSTOMER_PROFILE TO TESTER;


---------
--ANALYST
--------

GRANT CONNECT, CREATE SESSION to ANALYST;

GRANT SELECT ON SHRIYA_PROJECT.CASE_DETAILS to ANALYST;
GRANT SELECT ON SHRIYA_PROJECT.CUSTOMER_FEEDBACK to ANALYST;
GRANT SELECT ON SHRIYA_PROJECT.EMPLOYEE_WORK to ANALYST;
GRANT SELECT ON SHRIYA_PROJECT.GEO_DETAILS to ANALYST;
GRANT SELECT ON SHRIYA_PROJECT.PARTS to ANALYST;
GRANT SELECT ON SHRIYA_PROJECT.PRODUCT to ANALYST;
GRANT SELECT ON SHRIYA_PROJECT.SUBSCRIPTION to ANALYST;
GRANT SELECT ON SHRIYA_PROJECT.SUBSCRIPTION_RENEWAL to ANALYST;

GRANT ALL ON SHRIYA_PROJECT.TRANSACTION_HISTORY TO ANALYST;
GRANT ALL ON SHRIYA_PROJECT.V_CASE_DETAILS TO ANALYST;

--DEVELOPER
CREATE USER JARVIS IDENTIFIED BY CCMSdatabase123;
--TESTER
CREATE USER JAKE IDENTIFIED BY CCMSdatabase123;
--ANALYST
CREATE USER CALEB IDENTIFIED BY CCMSdatabase123;


